"""initial schema

Revision ID: 09b371db1470
Revises:
Create Date: 2026-08-01 14:21:02.479847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09b371db1470'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('projects',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('paper_title', sa.String(length=500), nullable=False),
    sa.Column('paper_path', sa.String(length=500), nullable=False),
    sa.Column('paper_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('improvement_targets', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('target_metrics', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('repo_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_table('experiments',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.String(length=20), nullable=False),
    sa.Column('parent_node_id', sa.String(length=20), nullable=True),
    sa.Column('git_branch', sa.String(length=100), nullable=False),
    sa.Column('improvement_description', sa.Text(), nullable=False),
    sa.Column('code_changes', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('report_html_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_project_id'), 'experiments', ['project_id'], unique=False)
    op.create_table('reference_papers',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('arxiv_id', sa.String(length=50), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('local_path', sa.String(length=500), nullable=True),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('key_contributions', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('download_status', sa.String(length=50), nullable=False),
    sa.Column('download_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reference_papers_project_id'), 'reference_papers', ['project_id'], unique=False)
    op.create_table('experiment_logs',
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_logs_experiment_id'), 'experiment_logs', ['experiment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_experiment_logs_experiment_id'), table_name='experiment_logs')
    op.drop_table('experiment_logs')
    op.drop_index(op.f('ix_reference_papers_project_id'), table_name='reference_papers')
    op.drop_table('reference_papers')
    op.drop_index(op.f('ix_experiments_project_id'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
